algoritmo "area_retangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2026
var
   base, altura, area: real
   
inicio

   escreva("Digite a base: ")
   leia(base)

   escreva("Digite a altura: ")
   leia(altura)

   area <- base * altura

   escreva("Área do retângulo: ", area)
   
fimalgoritmo