Algoritmo "Estrutura_de_decisao_simples"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa do Santos
// Descrição   : Estrutura de decisão, se o numero for menor que 10 ele vai informar
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   valor: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Escreva o valor:")
   leia(valor)
   se valor<10 entao
      escreval("O Numero digitado é menor que 10")
   fimse

Fimalgoritmo