Algoritmo "EstruturaDeRepeticao"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : TEste de estrutua de repetição
// Autor(a)    : Georgea Lacerda
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto contadora <10 faça  //vai aprentar o nome Georgea Lacerda ate a quantidade ser maior que 10 contadoras
escreval("Georgea Lacerda")
contadora<- contadora + 1
fimenquanto


Fimalgoritmo