Algoritmo "ExemploPara"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo Para
// Autor(a)    : Georgea Lacerda
// Data atual  : 14/04/2026
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Exemplo de Laço de Repetição Para")

   para contadora de 10 até 1 passo - faça
      Escreval(contadora)
   fimpara

Fimalgoritmo