Algoritmo "Mes_em_Dias"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa do Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   mes_ano: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Digite um numero que sera convertido em mês:")
   leia(mes_ano)
   se mes_ano = 1 entao
      escreva ("Janeiro")
   senao
      se mes_ano = 2   entao
         escreva ("Fevereiro")
      senao
         se mes_ano = 3 entao
            escreva ("Março")
         senao
            se mes_ano = 4  entao
               escreva ("Abril")

            fimse
         fimse
      fimse



Fimalgoritmo
