Algoritmo "Raio_do_Circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa do Santos 
// Descrição   : Calcula e exibe o valor do perimetro do ciruclo
// Autor(a)    : Georgea Lacerda
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   raio: real
   resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva ("Digite o valor do raio do circulo:")
     leia(raio)
     escreval("")
     resultado<- 2*3.14*raio
     escreva ("O valor do perimetro da cricuferencia é:", resultado)

Fimalgoritmo