Algoritmo "Repita"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa do Santos 
// Descrição   : Testa a função repita
// Autor(a)    : Georgea Lacerda
// Data atual  : 13/04/2026
Var
// Seção de Declarações das variáveis 
contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        contadora<- 1
        repita
        escreval("Georgea")
        contadora<- contadora+1
        ate contadora>11

Fimalgoritmo
